version: '3.1'

networks:
  todo-list-network:
    driver: bridge

services:

  todo-list-back-end:
    container_name: todo-list-back-end
    build:
      context: ./back-end
      dockerfile: Dockerfile
    depends_on:
      - mongo
    networks:
      - todo-list-network
    ports:
      - 8080:8080

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: todos
    networks:
      - todo-list-network
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    networks:
      - todo-list-network
