server:
  port: 8080

spring:
  data:
    mongodb:
      host: dojo-react_mongo_1
      port: 27017
      database: todos
      username: root
      password: example
      repositories:
        type: auto